name: Deploy Laravel to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy Laravel application
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@35.154.188.89 "cd /var/www/html/blogs && git pull origin main && composer install && php artisan migrate --force && php artisan config:cache && php artisan route:cache"


